"""Сервис парсинга и вывода инф о машинах

Revision ID: 6a5c8b45eb29
Revises: 
Create Date: 2026-03-31 21:44:08.324545

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6a5c8b45eb29'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_listing_id', sa.String(length=32), nullable=False, comment='Идентификатор объявления'),
    sa.Column('make', sa.String(length=255), nullable=False, comment='Производитель'),
    sa.Column('model', sa.String(length=512), nullable=False, comment='Модель авто'),
    sa.Column('year', sa.Integer(), nullable=False, comment='Год выпуска'),
    sa.Column('mileage_km', sa.Integer(), nullable=False, comment='Пробег авто'),
    sa.Column('price_man_won', sa.Integer(), nullable=False, comment='Цена на сайте'),
    sa.Column('currency', sa.String(length=8), nullable=False, comment='Валюта'),
    sa.Column('photos_json', sa.Text(), nullable=False, comment='URL картинок'),
    sa.Column('source_url', sa.String(length=1024), nullable=False, comment='Ссылка на страницу объявления'),
    sa.Column('title', sa.String(length=1024), nullable=False, comment='Заголовок для карточки'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активность'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания в БД'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата обновления в БД'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_is_active'), 'listings', ['is_active'], unique=False)
    op.create_index(op.f('ix_listings_mileage_km'), 'listings', ['mileage_km'], unique=False)
    op.create_index(op.f('ix_listings_price_man_won'), 'listings', ['price_man_won'], unique=False)
    op.create_index(op.f('ix_listings_source_listing_id'), 'listings', ['source_listing_id'], unique=True)
    op.create_index(op.f('ix_listings_year'), 'listings', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_year'), table_name='listings')
    op.drop_index(op.f('ix_listings_source_listing_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_price_man_won'), table_name='listings')
    op.drop_index(op.f('ix_listings_mileage_km'), table_name='listings')
    op.drop_index(op.f('ix_listings_is_active'), table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###